name = "BLASBenchmarksGPU"
uuid = "7f126dfc-02fe-4b0a-bf44-dbfefac359c9"
authors = ["Dilum Aluthge", "Chris Elrod", "Thomas Faingnaert", "Tim Besard", "contributors"]
version = "0.1.0-DEV"

[deps]
GemmKernels = "312cec97-f96c-4f55-a63d-8e567f91b59b"

[compat]
julia = "1.5"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[targets]
test = ["InteractiveUtils", "Test", "VectorizationBase"]
